site_name: Hobbit
theme: readthedocs
repo_url: http://github.com/hobbit-ai/hobbit
pages:
    - Home: index.md
    - First steps: first_steps.md
    - Hyperband: hyperband.md
    - Hyperparameters: hyperparameter.md
